---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Australia/Melbourne
      - JELLYFIN_PublishedServerUrl=https://screamingbird.duckdns.org
    group_add:
      - '303' # Add to "render" group to enable GPU accel
      - '100'
    volumes:
      - /Jellyfin:/config:rwx
      - /external-drive/Media:/data/media:rwx
    ports:
      - 8096:8096
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
    restart: unless-stopped
  mc-server:
    image: itzg/minecraft-server:latest
    container_name: minecraft-vanilla
    ports:
      - "25566:25565"
    environment:
      EULA: "TRUE"
      # Server settings
      MEMORY: "6G"
      TYPE: "VANILLA"
      VERSION: "26.2"
      DIFFICULTY: "hard"
      ICON: "https://soybooru.com/api/booru/posts/1025/file"
      LEVEL: "FatGoy"
      MOTD: "Fuck air and fuck water"
      SYNC_CHUNK_WRITES: true
    volumes:
      - ~/servers/minecraft-server/:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
