theme {
    style       = kvantum-dark
    icon_theme  = Papirus-Dark
    font        = JetBrainsMono Nerd Font
    font_fixed  = JetBrainsMono Nerd Font
}

misc {
    menus_have_icons = true
    single_click_activate   = true
}
