##################
## KITTY CONFIG ##
##################

# Set font
font_family         JetBrainsMono Nerd Font
bold_font           auto
italic_font         auto
bolt_italic_font    auto
font_size           12.0

# Initial window size
remember_window_size    no
initial_window_width    140c
initial_window_height   36c

# Appearance
background_opacity  0.95
include             tokyo-night-kitty.conf

# Misc
enable_audio_bell   no
scrollbar           never
