##################
## KITTY CONFIG ##
##################

# Set font
font_family         JetBrainsMono Nerd Font
bold_font           auto
italic_font         auto
bolt_italic_font    auto
font_size           12.0
